### ISSUE TITLE
Porównywanie baz danych

### ISSUE THREAD

**Issue by RegiachEW** [gracuss6O/POS_RFID#1]

**Comment by gracuss6O** [comment]
Wstępnie:
niekoniecznie jako skorzystanie z aplikacji dopisywać wpisane dane przez użytkownika do bazy danych na serwerze, proponuje zrobić kolejną bazę pt. Logi, gdzie będą zapisywane wpisane dane przez użytkownika wraz z próbą autoryzacji i np. informacją zwrotną czy był PASS/FAIL.  "data" z desktop app będzie porównywana z rekordami zawartymi w database
Ogarnąć sposób na porównanie PO WCIŚNIĘCIU PRZYCISKU
